-- This is a GitHub Actions workflow configuration, not SQL
name: Supabase Migrations

on:
  push:
    branches:
      - main
      - develop

jobs:
  migrations:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Supabase CLI
      uses: supabase/setup-cli@v1
    
    - name: Verify migration
      run: supabase db diff
    
    - name: Push migrations to staging
      if: github.ref == 'refs/heads/develop'
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        SUPABASE_PROJECT_ID: ${{ secrets.STAGING_PROJECT_ID }}
      run: supabase db push
    
    - name: Push migrations to production
      if: github.ref == 'refs/heads/main'
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        SUPABASE_PROJECT_ID: ${{ secrets.PRODUCTION_PROJECT_ID }}
      run: supabase db push
